{
 "title": "Kubernetes Nodes Mobile",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((avg by (instance) (node_memory_MemTotal_bytes{job=\"node\"}) - avg by (instance) (node_memory_MemAvailable_bytes{job=\"node\"})) / (avg by (instance) (node_memory_MemTotal_bytes{job=\"node\"}) )) * 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "avg by (instance) (node_cpu_scaling_frequency_hertz{job=\"node\"})",
     "legendFormat": "GHz"
    },
    {
     "expr": "((sum by (instance) (irate(node_cpu_seconds_total{job=\"node\"}[5m]) * 100) - sum by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"node\"}[5m]) * 100)) / sum by (instance) (irate(node_cpu_seconds_total{job=\"node\"}[5m]) * 100)) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg by (instance) (node_ipmi_temperature_celsius{sensor=\"Temp 1\"})",
     "legendFormat": "Ambient"
    },
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{sensor=\"temp3\",job=\"node\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "avg by (instance) (irate(node_network_receive_bytes_total{device=\"main\"}[5m]))",
     "legendFormat": "In"
    },
    {
     "expr": "avg by (instance) (irate(node_network_transmit_bytes_total{device=\"main\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "UPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "network_ups_tools_ups_power", "legendFormat": "Power" },
    {
     "expr": "network_ups_tools_battery_charge",
     "legendFormat": "Battery"
    }
   ]
  },
  {
   "title": "UPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime",
     "legendFormat": "runtime"
    },
    {
     "expr": "network_ups_tools_ups_status{flag=\"OL\"} >0 or network_ups_tools_ups_status{flag=\"OB\"} >0",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"k8spods2\",device=\"eth0\"}[5m])",
     "legendFormat": "In"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"k8spods2\",device=\"eth0\"}[5m])",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "Front Door", "type": "innius-video-panel", "gridPos": { "h": 12, "w": 7, "x": 17, "y": 6 } },
  {
   "title": "SAN",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/Main\"}",
     "legendFormat": "Free Space"
    },
    {
     "expr": "count(smartmon_device_info) - count(smartmon_device_smart_healthy)",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Gluster",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "volume_capacity_free_bytes", "legendFormat": "Free Space" },
    { "expr": "volume_health  ", "legendFormat": "Status" }
   ]
  }
 ]
}