---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homeassistant-container

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: homeassistant
  labels:
    app: homeassistant

spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      serviceAccountName: homeassistant-container
      containers:
        - name: homeassistant
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          image: homeassistant/home-assistant:stable
          ports:
            - name: 
              containerPort: 9090
          volumeMounts:
            - name: config            
              mountPath: /config
        - name: metrics
          imagePullPolicy: IfNotPresent
          image: quay.io/prometheus/node-exporter
          ports:
            - name: metrics
              containerPort: 9100
      volumes:
        - name: config
          glusterfs:
            endpoints: glusterfs-cluster
            path: data/homeassistant/
            readOnly: false
      dnsPolicy: "ClusterFirst"

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  type: ClusterIP
  selector:
    app: homeassistant
  ports:
    - protocol: TCP
      port: 8123
      name: secure
      targetPort: 8123
    - protocol: TCP
      port: 9100
      name: metrics
      targetPort: 9100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: smart.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 8123
