---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-container

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      serviceAccountName: minecraft-container
      containers:
        - name: minecraft
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          imagePullPolicy: IfNotPresent
          image: minecraft/minecraft:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - name: 
              containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /var/lib/minecraft
        - name: metrics
          imagePullPolicy: IfNotPresent
          image: quay.io/prometheus/node-exporter:latest
          ports:
            - name: metrics
              containerPort: 9100
      volumes:
        - name: data
          glusterfs:
            endpoints: glusterfs-cluster
            path: data/minecraft
            readOnly: false
      dnsPolicy: "ClusterFirst"

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: ClusterIP
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 3000
      name: secure
      targetPort: 3000
    - protocol: TCP
      port: 9100
      name: metrics
      targetPort: 9100

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - host: minecraft.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minecraft
            port:
              number: 3000
